package com.asterism.event;

public enum DomainEventType {
    UserMessageReceived,
    PRDUpdated,
    ClarificationRequested,
    PRDConfirmed,
    OwnerApprovalRequested,
    OwnerApprovalSignalSubmitted,
    TemporalCaseStarted,
    TemporalCaseStartFailed,
    TemporalSignalSubmitted,
    TemporalSignalFailed,
    WorkItemActivated,
    ReworkStarted,
    ExecutionPlanDrafted,
    AgentStageCompleted,
    WorkItemRejected,
    ModificationCompleted,
    WorkerBlocked,
    PatchApplied,
    PatchApplyBlocked,
    PatchRejected,
    ValidationPassed,
    ValidationFailed,
    ReleaseCompleted,
    CaseCancelled,
    MemoryCandidateCreated,
    MemoryApproved,
    MemoryRejected,
    MemoryDisabled,
    ContextSnapshotCreated
}
